### ISSUE TITLE
Automated tests for user

### ISSUE THREAD

**Issue by Tohuvavohu** [BjoernBiltzinger/pyspi#18]
I see there is continous integration and automated testing enabled for this project, and as a user I was successfully able to run the manual tests.
However, I think in the spirit of the 'automated testing by user' implied by the review criteria: https://joss.readthedocs.io/en/latest/review_criteria.html
it would be useful and more complete to have a very simple end-user runnable test script, that one can run post local installation to automatically run through the tests in the pyspi.test package.
https://github.com/openjournals/joss-reviews/issues/4017

**Comment by grburgess** [comment]
@Tohuvavohu have you tried running pytest -v in the top level directory? Or do you mean you would like separate scripts that can be run directly?

**Comment by Tohuvavohu** [comment]
@grburgess I'd not used pytest before, and was unfamiliar with it.  :)
I ended up just running the test scripts in the test directory manually. 

If you include one line in the documentation or README directing the user to do this, I can consider this issue addressed.
As it is, there is no mention of *how to run the tests* in any of the docs (although they are documented in the API).

**Comment by grburgess** [comment]
@Tohuvavohu good idea! But in general, if there is a test directory and the proper specification in the setup scripts, you can install and run pytest and it will give you a report. For example see: https://github.com/BjoernBiltzinger/pyspi/blob/master/.github/workflows/publish_pypi.yml#L107

It gives a nice visual output as well
