### ISSUE TITLE
Minor comments and suggestions for JOSS review

### ISSUE THREAD

**Issue by dfm** [BjoernBiltzinger/pyspi#19]
As part of my review for https://github.com/openjournals/joss-reviews/issues/4017, I'm going to collect minor comments and suggestions here in this issue. I'll keep adding to this list as I go, and if required, I'll open separate issues if anything more major comes up.

- [x] Related to "A statement of need" checklist item: I think that the paper clearly specifies this need, but the online documentation would be improved with some of this text included on the landing page.
- [x] It would also be useful to add a link to the docs from the top right corner of the GitHub landing page. Currently the only link there is to 3ML and I repeatedly clicked on that when I wanted to go to the docs for PySPI.
- [x] In [this section of the installation docs](https://pyspi.readthedocs.io/en/latest/notebooks/installation/#Environment-Variables), it's not clear what the `/path/to/external/datafolder` is for and what it should be set to. Some clarification would be useful.
- [x] Throughout the docs, the various data products are often visualized using built in functions (e.g. `.view_lightcurve` for light curves), but I think it would also be useful to demonstrate how to actually access the underlying data (as a numpy array or something) which doesn't always seem clear from the examples. I'm an outsider to the field, but I know that in my research I generally want to access the underlying data, not just see the nicely formatted plots!

**Comment by BjoernBiltzinger** [comment]
I addressed all three mentioned points in the latest version of the Docs and the Github repo.

**Comment by dfm** [comment]
Great - I think that the third one could use a little more explanation (what data files are going to go in each directory? what happens if you make them the same? why are there two directories? how big do we expect them to get? etc.)

I've also added one more general comment that could use some thought.

**Comment by BjoernBiltzinger** [comment]
For Point 3: I added a few more info about what files are downloaded and how large the directory gets.
For Point 4: I added a section in the Docs for this: https://pyspi.readthedocs.io/en/latest/notebooks/access_data/

**Comment by dfm** [comment]
Awesome - looks good to me!
