### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by dfm** [BjoernBiltzinger/pyspi#21]
The `pip install py-spi` command fails in a fresh conda environment on my Mac with an HDF5 compilation error. Given the dependencies on things like `h5py` and `numba` that don't always have great `pip` support, I'd recommend adding some dependency comments to the docs. In particular, given the huge number of dependencies (many of them compiled) I think it would be useful for a lot of users to have a `conda` environment or command to get started fast.

For example, the following `conda` / `mamba` environment worked for me:

```bash
mamba create -n pyspi -c conda-forge python=3.9 numpy scipy ipython numba astropy matplotlib h5py pandas pytables
```

These aren't all the dependencies, of course, and not all necessarily need to be installed with `conda`, but this might be somewhere to start?

Ref: https://github.com/openjournals/joss-reviews/issues/4017

**Comment by BjoernBiltzinger** [comment]
I could not reproduce this problem. On my Ubuntu laptop `pip install py-spi` works fine in a fresh `conda`/`mamba` environment. I also added a test to the CI, that tests this for a fresh `conda` environment on the latests ubuntu and MacOS versions and the tests also pass (https://github.com/BjoernBiltzinger/pyspi/actions/workflows/pip_install.yml). Nevertheless I added a comment in the installation section of the Docs with the command that worked for you, in case someone else gets the same error. (https://pyspi.readthedocs.io/en/latest/notebooks/installation/)
