### ISSUE TITLE
Running unit tests locally

### ISSUE THREAD

**Issue by dfm** [BjoernBiltzinger/pyspi#24]
As mentioned by @Tohuvavohu over in #18, the docs don't seem to currently describe the workflow for running the unit tests locally. It would be good to include this, and in particular, just running pytest doesn't work without `pytest-cov` installed. The docs should be clear about what the expected steps are.

Ref: https://github.com/openjournals/joss-reviews/issues/4017

**Comment by BjoernBiltzinger** [comment]
I added a subsection on the landing page of the documentation on how to run the tests locally: https://pyspi.readthedocs.io/en/latest/

**Comment by dfm** [comment]
Good, but I think it would be better to just move that to the bottom of the "installation" page, since all of that setup will be necessary first. What do you think?

**Comment by BjoernBiltzinger** [comment]
Yes I agree, I moved that part to the installation page in the docs.
